# Generated by Django 5.1.5 on 2025-02-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
